#proxy server config
proxy:
  port: 9304
  timeout: #proxy read and write timeout
    write: 5
    read: 5
  redirctTyp: temp #redirect type [temp,perm], temp:temporary redirect,perm:permanently moved
  strategy: polling #redirect stratery:[loop,weight,location]

#health check
health:
  type: host #[host,port,url]
  url: GET /test #required if type is 'url'

#servers
servers:
  - host: www.baidu.com
    port: 80
    weight: 1
  - host: www.so.com
    port: 80
    weight: 1

#enviroment
enviroment: debug  #debug product